# Plex

networks:
  t2_proxy:
    external: true

services:
  # Plex Meta Manager - Metadata Management
  plex-meta-manager:
    image: lscr.io/linuxserver/plex-meta-manager:latest
    container_name: plex-meta-manager
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - t2_proxy
    volumes:
      - ${DOCKERDIR:-/opt/docker}/appdata/plex-meta-manager:/config
      - ${DATADIR:-/data}:/data
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    labels:
      - sablier.enable=true
      - sablier.group=mygroup
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.plex-meta-manager-rtr.entrypoints=https"
      - "traefik.http.routers.plex-meta-manager-rtr.rule=Host(`pmm.${DOMAINNAME_CLOUD_SERVER}`)"
      ## Middlewares
      - "traefik.http.routers.plex-meta-manager-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.plex-meta-manager-rtr.service=plex-meta-manager-svc"
      - "traefik.http.services.plex-meta-manager-svc.loadbalancer.server.port=8000"
      ## Homepage
      - homepage.group=Media
      - homepage.name=Plex Meta Manager
      - homepage.icon=plex-meta-manager.png
      - homepage.href=https://pmm.${DOMAINNAME_CLOUD_SERVER}
      - homepage.description=Metadata Management
      - homepage.weight=7

  # Plex Media Server
  plex:
    image: plexinc/pms-docker:latest
    container_name: plex
    # security_opt:
    #   - no-new-privileges:true
    restart: "no"
    profiles: ["media", "all"]
    networks:
      - t2_proxy
    ports:
      - "32400:32400/tcp"
      - "3005:3005/tcp"
      - "8324:8324/tcp"
      - "32469:32469/tcp"
      - "1900:1900/udp" # conflicts with xTeVe and Synology default ports
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "33400:33400/tcp"
    devices:
      - /dev/dri:/dev/dri # for hardware transcoding
    volumes:
      - $DOCKERDIR/appdata/plex:/config
      - $DOWNLOADSDIR:/data/downloads
      - $DATADIR:/data/media
      # - $EXTDRIVE/ssd/sitespeed:/data/files
      - /dev/shm:/transcode # Offload transcoding to RAM if you have enough RAM
    environment:
      TZ: $TZ
      HOSTNAME: "sPlex"
      # PLEX_CLAIM_FILE: /run/secrets/plex_claim
      PLEX_UID: $PUID
      PLEX_GID: $PGID
      ADVERTISE_IP: "http://$SERVER_IP:32400/,http://$SERVER_IP_LOCAL:32400,https://splex.$DOMAINNAME_CLOUD_SERVER"
      # ALLOWED_NETWORKS: $LOCAL_NETWORK
    secrets:
      - plex_claim
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.plex-rtr.entrypoints=https"
      - "traefik.http.routers.plex-rtr.rule=Host(`splex.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.plex-rtr.middlewares=chain-no-auth@file"
      ## HTTP Services
      - "traefik.http.routers.plex-rtr.service=plex-svc"
      - "traefik.http.services.plex-svc.loadbalancer.server.port=32400"
      ## Homepage
      - homepage.group=Media
      - homepage.name=Plex
      - homepage.icon=plex.png
      - homepage.href=https://splex.mirwin.net
      - homepage.description=Plex
      # - homepage.weight=1
      - homepage.widget.type=plex
      - homepage.widget.url=http://plex:32400
      - homepage.widget.key=${PLEX_API_KEY}

  # Tautulli - Plex Statistics
  tautulli:
    image: lscr.io/linuxserver/tautulli:latest
    container_name: tautulli
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "media", "all"]
    networks:
      - t2_proxy
    ports:
      - "8181:8181"
    volumes:
      - ${DOCKERDIR:-/opt/docker}/appdata/tautulli:/config
      - ${DOCKERDIR:-/opt/docker}/appdata/plex/Library/Application Support/Plex Media Server/Logs:/logs:ro
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8181/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.tautulli-rtr.entrypoints=https"
      - "traefik.http.routers.tautulli-rtr.rule=Host(`tautulli.${DOMAINNAME_CLOUD_SERVER}`)"
      ## Middlewares
      - "traefik.http.routers.tautulli-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.tautulli-rtr.service=tautulli-svc"
      - "traefik.http.services.tautulli-svc.loadbalancer.server.port=8181"
      ## Homepage
      - homepage.group=Media
      - homepage.name=Tautulli
      - homepage.icon=tautulli.png
      - homepage.href=https://tautulli.${DOMAINNAME_CLOUD_SERVER}
      - homepage.description=Plex Statistics
      - homepage.weight=8 