version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:8.9.0 # bbilly1/tubearchivist-es
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=$ELASTIC_PASSWORD"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - $DOCKERDIR/appdata/elasticsearch:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"

  # MariaDB - MySQL Database
  # After starting container for first time dexec and mysqladmin -u root password <password>
  # mariadb:
  #   container_name: mariadb # mariadb:10.6
  #   image: lscr.io/linuxserver/mariadb
  #   # security_opt:
  #   #   - no-new-privileges:true
  #   restart: unless-stopped
  #   profiles: ["core", "all"]
  #   networks:
  #     - t2_proxy
  #   ports:
  #     - "$DB_PORT:3306"
  #   volumes:
  #     - $DOCKERDIR/appdata/mariadb/data:/config
  #     # - db:/var/lib/mysql
  #   environment:
  #     TZ: $TZ
  #     PUID: $PUID
  #     PGID: $PGID
  #     FILE__MYSQL_ROOT_PASSWORD: /run/secrets/mysql_root_password # Note FILE__ (double underscore) - Issue #127
  #     # - MYSQL_ROOT_PASSWORD=
  #     # - MYSQL_PASSWORD=
  #     # - MYSQL_DATABASE=nextcloud
  #     # - MYSQL_USER=nextcloud
  #   secrets:
  #     - mysql_root_password
    # command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW

  # phpMyAdmin - Database management
  # Create a new user with admin privileges. Cannot login as MySQL root for some reason.
  # phpmyadmin:
  #   image: phpmyadmin/phpmyadmin:latest
  #   container_name: phpmyadmin
  #   # security_opt:
  #   #   - no-new-privileges:true
  #   restart: unless-stopped
  #   profiles: ["apps", "all"]
  #   networks:
  #     - t2_proxy
  #   environment:
  #     - PMA_HOST=$DB_HOST
  #     - PMA_PORT=$DB_PORT
  #     #- PMA_ARBITRARY=1
  #     - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql_root_password
  #   secrets:
  #     - mysql_root_password
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.phpmyadmin-rtr.entrypoints=https"
  #     - "traefik.http.routers.phpmyadmin-rtr.rule=Host(`pma.$DOMAINNAME_CLOUD_SERVER`)"
  #     ## Middlewares
  #     - "traefik.http.routers.phpmyadmin-rtr.middlewares=chain-oauth@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.phpmyadmin-rtr.service=phpmyadmin-svc"
  #     - "traefik.http.services.phpmyadmin-svc.loadbalancer.server.port=80"
  #     ## Homepage
  #     - homepage.group=Admin
  #     - homepage.name=phpMyAdmin
  #     - homepage.icon=phpmyadmin.png
  #     - homepage.href=https://pma.mirwin.net
  #     - homepage.description=Database administration
  #     - homepage.weight=3

  # Redis - Key-value Store
  redis:
    container_name: redis
    image: redis:latest # redis:alpine
    # security_opt:
    #   - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - t2_proxy
    # command: redis-server --save "" --appendonly "no"
    entrypoint: redis-server --appendonly yes --maxmemory 1073741824 --maxmemory-policy allkeys-lru # --requirepass $REDIS_PASSWORD 
    ports:
      - "6379:6379"
    # tmpfs:
    #   - /var/lib/redis
    # cap_drop:
    #   - ALL
    # cap_add:
    #   - SETGID
    #   - SETUID
    #   - DAC_OVERRIDE
    volumes:
      - $DOCKERDIR/appdata/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
