# version: "3.9"

services:
  nzbget:
    container_name: nzbget
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID:-1000}
      TZ: ${TZ:-UTC}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - wget
      - --no-verbose
      - --tries=1
      - --spider
      - http://localhost:6789/
      timeout: 10s
    image: lscr.io/linuxserver/nzbget:latest
    labels:
    - sablier.enable=true
    - sablier.group=mygroup
    - traefik.enable=true
    - traefik.http.routers.nzbget-rtr.entrypoints=https
    - traefik.http.routers.nzbget-rtr.rule=Host(`nzbget.${DOMAINNAME_CLOUD_SERVER}`)
    - traefik.http.routers.nzbget-rtr.middlewares=chain-oauth@file
    - traefik.http.routers.nzbget-rtr.service=nzbget-svc
    - traefik.http.services.nzbget-svc.loadbalancer.server.port=6789
    - homepage.group=Downloaders
    - homepage.name=NZBGet
    - homepage.icon=nzbget.png
    - homepage.href=https://nzbget.${DOMAINNAME_CLOUD_SERVER}
    - homepage.description=Usenet downloader
    - homepage.weight=5
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: 10m
        tag: '{{.Name}}'
    networks:
    - t2_proxy
    ports:
    - ${NZBGET_PORT:-6789}:6789
    profiles:
    - downloads
    - all
    restart: unless-stopped
    volumes:
    - ${DOCKERDIR:-/opt/docker}/appdata/nzbget:/config
    - $DATADIR/Downloads:/downloads
    - $DATADIR/Intermediates:/intermediates
    - $DATADIR/NZB:/nzb

  # SABnzbd - Binary newsgrabber (NZB downloader)
  # Disable SABNnzbd's built-in HTTPS support for traefik proxy to work
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    # security_opt:
    #   - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "downloads", "all"]
    networks:
      - t2_proxy
    ports:
      - "8084:8080"
    volumes:
      - ${DOCKERDIR:-/opt/docker}/appdata/sabnzbd:/config
      # - ${DATADIR:-/data}:/data/
      - ${DOWNLOADSDIR:-/downloads}:/data/downloads
      - $DATADIR/incomplete:/data/incomplete
      - $DATADIR/complete:/data/complete
    environment:
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
      TZ: ${TZ:-UTC}
      UMASK_SET: 002
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.sabnzbd-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.sabnzbd-rtr-bypass.rule=Host(`sabnzbd.${DOMAINNAME_CLOUD_SERVER}`) && Query(`apikey`, `$SABNZBD_API_KEY`)"
      - "traefik.http.routers.sabnzbd-rtr-bypass.rule=Host(`sabnzbd.${DOMAINNAME_CLOUD_SERVER}`) && Headers(`traefik-auth-bypass-key`, `$TRAEFIK_AUTH_BYPASS_KEY`)"  # Bypass Auth for LunaSea on iOS
      - "traefik.http.routers.sabnzbd-rtr-bypass.priority=100"
      ## HTTP Routers Auth
      - "traefik.http.routers.sabnzbd-rtr.entrypoints=https"
      - "traefik.http.routers.sabnzbd-rtr.rule=Host(`sabnzbd.${DOMAINNAME_CLOUD_SERVER}`)"
      - "traefik.http.routers.sabnzbd-rtr.priority=99"
      ## Middlewares
      - "traefik.http.routers.sabnzbd-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.sabnzbd-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.sabnzbd-rtr.service=sabnzbd-svc"
      - "traefik.http.routers.sabnzbd-rtr-bypass.service=sabnzbd-svc"
      - "traefik.http.services.sabnzbd-svc.loadbalancer.server.port=8080"
      ## Homepage
      - homepage.group=Downloaders
      - homepage.name=Sabnzbd
      - homepage.icon=sabnzbd.png
      - homepage.href=https://sabnzbd.${DOMAINNAME_CLOUD_SERVER}
      - homepage.description=Usenet downloader
      - homepage.weight=1
      # - homepage.widget.type=sabnzbd
      # - homepage.widget.url=http://sabnzbd:8080/
      # - homepage.widget.key=${SABNZBD_API_KEY}
