networks:
  t2_proxy:
    external: true
services:
  qbittorrent:
    container_name: qbittorrent
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID:-1000}
      TZ: ${TZ:-UTC}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - wget
      - --no-verbose
      - --tries=1
      - --spider
      - http://localhost:8080/
      timeout: 10s
    image: lscr.io/linuxserver/qbittorrent:latest
    labels:
    - sablier.enable=true
    - sablier.group=mygroup
    - traefik.enable=true
    - traefik.http.routers.qbittorrent-rtr.entrypoints=https
    - traefik.http.routers.qbittorrent-rtr.rule=Host(`qbittorrent.${DOMAINNAME_CLOUD_SERVER}`)
    - traefik.http.routers.qbittorrent-rtr.middlewares=chain-oauth@file
    - traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc
    - traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8080
    - homepage.group=Downloaders
    - homepage.name=qBittorrent
    - homepage.icon=qbittorrent.png
    - homepage.href=https://qbittorrent.${DOMAINNAME_CLOUD_SERVER}
    - homepage.description=BitTorrent client
    - homepage.weight=3
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: 10m
        tag: '{{.Name}}'
    networks:
    - t2_proxy
    ports:
    - ${QBITTORRENT_PORT:-8080}:8080
    - 6881:6881
    - 6881:6881/udp
    profiles:
    - downloads
    - all
    restart: unless-stopped
    volumes:
    - ${DOCKERDIR:-/opt/docker}/appdata/qbittorrent:/config
    - $DATADIR/Downloads:/downloads

  transmission:
    container_name: transmission
    environment:
      PGID: ${PGID:-1000}
      PUID: ${PUID:-1000}
      TZ: ${TZ:-UTC}
    healthcheck:
      interval: 30s
      retries: 3
      start_period: 40s
      test:
      - CMD
      - wget
      - --no-verbose
      - --tries=1
      - --spider
      - http://localhost:9091/
      timeout: 10s
    image: lscr.io/linuxserver/transmission:latest
    labels:
    - sablier.enable=true
    - sablier.group=mygroup
    - traefik.enable=true
    - traefik.http.routers.transmission-rtr.entrypoints=https
    - traefik.http.routers.transmission-rtr.rule=Host(`transmission.${DOMAINNAME_CLOUD_SERVER}`)
    - traefik.http.routers.transmission-rtr.middlewares=chain-oauth@file
    - traefik.http.routers.transmission-rtr.service=transmission-svc
    - traefik.http.services.transmission-svc.loadbalancer.server.port=9091
    - homepage.group=Downloaders
    - homepage.name=Transmission
    - homepage.icon=transmission.png
    - homepage.href=https://transmission.${DOMAINNAME_CLOUD_SERVER}
    - homepage.description=BitTorrent client
    - homepage.weight=4
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: 10m
        tag: '{{.Name}}'
    networks:
    - t2_proxy
    ports:
    - ${TRANSMISSION_PORT:-9091}:9091
    - 51413:51413
    - 51413:51413/udp
    profiles:
    - downloads
    - all
    restart: unless-stopped
    volumes:
    - ${DOCKERDIR:-/opt/docker}/appdata/transmission:/config
    - $DATADIR/Downloads:/downloads
    - $DATADIR/Watch:/watch
