# version: "3.9"

services:
  # https://github.com/jesec/flood/wiki/Run-rTorrent-and-Flood-via-Docker
  # flood:
  #   image: jesec/flood
  #   container_name: flood
  #   user: $PUID:$PGID
  #   restart: unless-stopped
  #   profiles: ["apps", "downloads", "all"]
  #   command: --port $FLOOD_PORT --allowedpath /data
  #   networks:
  #     - t2_proxy
  #   environment:
  #     HOME: /config
  #   volumes:
  #     - $DOCKERDIR/appdata/flood:/config
  #     - $DOWNLOADSDIR:/data
  #   ports:
  #     - $FLOOD_PORT:$FLOOD_PORT
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.flood-rtr.entrypoints=https"
  #     - "traefik.http.routers.flood-rtr.rule=Host(`flood.$DOMAINNAME_CLOUD_SERVER`)"
  #     ## Middlewares
  #     - "traefik.http.routers.flood-rtr.middlewares=chain-oauth@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.flood-rtr.service=flood-svc"
  #     - "traefik.http.services.flood-svc.loadbalancer.server.port=$FLOOD_PORT"
  #     # Homepage
  #     - homepage.group=Downloaders
  #     - homepage.name=Flood
  #     - homepage.icon=flood.png
  #     - homepage.href=https://flood.mirwin.net
  #     - homepage.description=BitTorrent client
  #     - homepage.weight=2

  geoip-updater:
    image: crazymax/geoip-updater:latest
    container_name: geoip-updater
    restart: always
    profiles: ["apps", "downloads", "all"]
    networks:
      - t2_proxy
    volumes:
      - "$DOCKERDIR/appdata/geoip:/data"
    env_file:
      - "env/geoip-updater.env"
      - ".env"


  # Gluetun - VPN Client for Docker Containers and More
  # Gluetun only for use by torrent clients + on demand lan devices.
  # Arr apps do not need VPN (not recommended), unless you have ISP/country restrictions.
  gluetun:
    image: qmcgaw/gluetun
    container_name: gluetun
    # security_opt:
    #   - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "apps", "downloads", "all"]
    networks:
      - t2_proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "13087:8080" # Exposing qBittorrent through Docker Host LAN IP
    #   - 8888:8888/tcp # HTTP proxy
    #   - 8388:8388/tcp # Shadowsocks
    #   - 8388:8388/udp # Shadowsocks
    volumes:
      - $DOCKERDIR/appdata/gluetun:/gluetun
    environment:
      TZ: $TZ

      # Wireguard
      VPN_SERVICE_PROVIDER: surfshark
      VPN_TYPE: wireguard
      WIREGUARD_PRIVATE_KEY: $SURFSHARK_WG_PRIVATE_KEY
      WIREGUARD_ADDRESSES: 10.14.0.2/16
      SERVER_COUNTRIES: Netherlands

    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.gluetun-qbittorrent-rtr.entrypoints=https"
      - "traefik.http.routers.gluetun-qbittorrent-rtr.rule=Host(`qbit.$DOMAINNAME_CLOUD_SERVER`)" # qBittorrent
      ## Middlewares
      - "traefik.http.routers.gluetun-qbittorrent-rtr.middlewares=chain-oauth@file" # qBittorrent
      ## HTTP Services
      - "traefik.http.routers.gluetun-qbittorrent-rtr.service=gluetun-svc" # qBittorrent
      - "traefik.http.services.gluetun-svc.loadbalancer.server.port=8080" # qBittorrent
      ## Homepage
      - homepage.group=Downloaders
      - homepage.name=Gluetun
      - homepage.icon=gluetun.png
      - homepage.href=https://qbit.mirwin.net
      - homepage.description=BitTorrent Client UI
      - homepage.weight=3
      - homepage.widget.type=gluetun
      - homepage.widget.url=http://gluetun:8080

  rapidbay:
    image: hauxir/rapidbay
    container_name: rapidbay
    restart: unless-stopped
    profiles: ["core", "apps", "downloads", "all"]
    networks:
      - t2_proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - "5002:5000"
    volumes:
      - $DOCKERDIR/appdata/rapidbay:/rapidbay
    environment:
      TZ: $TZ
      JACKETT_HOST: jackett.$DOMAINNAME_CLOUD_SERVER
      JACKETT_API_KEY: $JACKETT_API_KEY

    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.rapidbay-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.rapidbay-rtr-bypass.priority=100"
      ## HTTP Routers Auth
      - "traefik.http.routers.rapidbay-rtr.entrypoints=https"
      - "traefik.http.routers.rapidbay-rtr.rule=Host(`rapidbay.$DOMAINNAME_CLOUD_SERVER`)"
      - "traefik.http.routers.rapidbay-rtr.priority=99"
      ## Middlewares
      - "traefik.http.routers.rapidbay-rtr-bypass.middlewares=chain-no-auth@file"
      - "traefik.http.routers.rapidbay-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.rapidbay-rtr.service=rapidbay-svc"
      - "traefik.http.routers.rapidbay-rtr-bypass.service=rapidbay-svc"
      - "traefik.http.services.rapidbay-svc.loadbalancer.server.port=5000"

      ## Homepage
      - homepage.group=Downloaders
      - homepage.name=RapidBay
      - homepage.icon=rapidbay.png
      - homepage.href=https://rapidbay.mirwin.net
      - homepage.description=BitTorrent Streaming
      - homepage.weight=3
      # - homepage.widget.type=rapidbay
      # - homepage.widget.url=http://rapidbay:5000

