networks:
  t2_proxy:
    external: true

services:
  # uptime-kuma:
  #   container_name: uptime-kuma
  #   environment:
  #     TZ: ${TZ:-UTC}
  #   healthcheck:
  #     interval: 30s
  #     retries: 3
  #     start_period: 40s
  #     test:
  #     - CMD
  #     - wget
  #     - --no-verbose
  #     - --tries=1
  #     - --spider
  #     - http://localhost:3001/
  #     timeout: 10s
  #   image: louislam/uptime-kuma:latest
  #   labels:
  #   - sablier.enable=true
  #   - sablier.group=mygroup
  #   - traefik.enable=true
  #   - traefik.http.routers.uptime-kuma-rtr.entrypoints=https
  #   - traefik.http.routers.uptime-kuma-rtr.rule=Host(`uptime.${DOMAINNAME_CLOUD_SERVER}`)
  #   - traefik.http.routers.uptime-kuma-rtr.middlewares=chain-oauth@file
  #   - traefik.http.routers.uptime-kuma-rtr.service=uptime-kuma-svc
  #   - traefik.http.services.uptime-kuma-svc.loadbalancer.server.port=3001
  #   - homepage.group=Monitoring
  #   - homepage.name=Uptime Kuma
  #   - homepage.icon=uptime-kuma.png
  #   - homepage.href=https://uptime.${DOMAINNAME_CLOUD_SERVER}
  #   - homepage.description=Uptime monitoring
  #   - homepage.weight=5
  #   logging:
  #     driver: json-file
  #     options:
  #       max-file: "3"
  #       max-size: 10m
  #       tag: '{{.Name}}'
  #   networks:
  #   - t2_proxy
  #   ports:
  #   - ${UPTIME_KUMA_PORT:-3001}:3001
  #   profiles:
  #   - monitoring
  #   - all
  #   restart: unless-stopped
  #   volumes:
  #   - ${DOCKERDIR:-/opt/docker}/appdata/uptime-kuma:/app/data
