version: "3.9"

# volumes:
#   ipfs_path:
#   ipfs_fuse:
#   ipns_fuse:
#   data:
#     name: tor-datadir-${TOR_OR_PORT}-${TOR_PT_PORT} # appdir/tor

services:
  freshrss:
    image: freshrss/freshrss:latest
    container_name: freshrss
    hostname: freshrss
    restart: unless-stopped
    profiles: ["tools", "web", "all"]
    # Optional build section if you want to build the image locally:
    # build:
    #   # Pick #latest (stable release) or #edge (rolling release) or a specific release like #1.21.0
    #   context: https://github.com/FreshRSS/FreshRSS.git#latest
    #   dockerfile: Docker/Dockerfile-Alpine
    logging:
      options:
        max-size: 10m
    volumes:
      - $DOCKERDIR/appdata/freshrss:/var/www/FreshRSS/data
      # - $DATADIR/media:/var/www/FreshRSS/data
      - $DOCKERDIR/appdata/freshrss/extensions:/var/www/FreshRSS/extensions
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      CRON_MIN: '3,33'
      TRUSTED_PROXY: 172.16.0.1/12 192.168.0.1/16 10.0.0.0/8
    networks:
      - t2_proxy
    ports:
      - "8765:80"
    labels:
      - sablier.enable=true
      - sablier.group=mygroup
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.freshrss-rtr.entrypoints=https"
      - "traefik.http.routers.freshrss-rtr.rule=Host(`freshrss.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.freshrss-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.freshrss-rtr.service=freshrss-svc"
      - "traefik.http.services.freshrss-svc.loadbalancer.server.port=80"
      ## Homepage
      - homepage.group=Tools
      - homepage.name=FreshRSS
      - homepage.icon=freshrss.png
      - homepage.href=https://freshrss.mirwin.net
      - homepage.description=Blog feeds
      - homepage.weight=4
      # - homepage.widget.type=freshrss
      # - homepage.widget.url=http://freshrss:8765
      # - homepage.widget.key=${FRESHRSS_API_KEY}

  # Ladder - 12ft.io cline, website to circumvent paywalls
  ladder:
    image: ghcr.io/kubero-dev/ladder:latest
    container_name: ladder
    # build: .
    restart: unless-stopped
    profiles: ["tools", "web", "all"]
    networks:
      - t2_proxy
    #command: sh -c ./ladder
    environment:
      - PORT=8091
      #- PREFORK=true
      #- X_FORWARDED_FOR=66.249.66.1
      #- USER_AGENT=Mozilla/5.0 (compatible; Googlebot/2.1; +http://www.google.com/bot.html)
      #- USERPASS=foo:bar
      - LOG_URLS=true
      #- GODEBUG=netdns=go
    ports:
      - "8091:8091"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 512M
        reservations:
          cpus: "0.25"
          memory: 128M
    labels:
      - sablier.enable=true
      - sablier.group=mygroup
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.ladder-rtr.entrypoints=https"
      - "traefik.http.routers.ladder-rtr.rule=Host(`ladder.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.ladder-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.ladder-rtr.service=ladder-svc"
      - "traefik.http.services.ladder-svc.loadbalancer.server.port=8091"
      ## Homepage
      - homepage.group=Tools
      - homepage.name=Ladder
      - homepage.icon=ladder.png
      - homepage.href=https://ladder.mirwin.net
      - homepage.description=Paywall bypass
      # - homepage.weight=2

  # via https://github.com/printfuck/xExtension-Readable
  readability:
    image: phpdockerio/readability-js-server
    container_name: readability
    restart: unless-stopped
    profiles: ["tools", "all"]
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.readability-rtr.entrypoints=https"
      - "traefik.http.routers.readability-rtr.rule=Host(`readability.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.readability-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.readability-rtr.service=readability-svc"
      - "traefik.http.services.readability-svc.loadbalancer.server.port=3000"

  # via https://github.com/printfuck/xExtension-Readable
  mercury:
    image: wangqiru/mercury-parser-api
    container_name: mercury
    restart: unless-stopped
    profiles: ["tools", "all"]
    ports:
      - 127.0.0.1:3001:3000
    networks:
      - t2_proxy
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.mercury-rtr.entrypoints=https"
      - "traefik.http.routers.mercury-rtr.rule=Host(`mercury.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.mercury-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.mercury-rtr.service=mercury-svc"
      - "traefik.http.services.mercury-svc.loadbalancer.server.port=3000"

  # FlareSolverr - Proxy server to bypass Cloudflare protection
  # Not sure if I need this or not. Just testing.
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    profiles: ["tools", "all"]
    networks:
      t2_proxy:
        ipv4_address: 192.168.90.160
    environment:
      LOG_LEVEL: info
      LOG_HTML: false
      CAPTCHA_SOLVER: none
      TZ: $TZ
    ports:
     - "8191:8191"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.flaresolverr-rtr.entrypoints=https"
      - "traefik.http.routers.flaresolverr-rtr.rule=Host(`flaresolverr.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.flaresolverr-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.flaresolverr-rtr.service=flaresolverr-svc"
      - "traefik.http.services.flaresolverr-svc.loadbalancer.server.port=80"

  # lounge - irc client
  lounge:
    image: ghcr.io/thelounge/thelounge:latest
    container_name: lounge
    profiles: ["tools", "all"]
    networks:
      - t2_proxy
    ports:
      - "9003:9000"
    restart: always
    volumes:
      - $DOCKERDIR/appdata/lounge:/var/opt/thelounge
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.lounge-rtr.entrypoints=https"
      - "traefik.http.routers.lounge-rtr.rule=Host(`lounge.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.lounge-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.lounge-rtr.service=lounge-svc"
      - "traefik.http.services.lounge-svc.loadbalancer.server.port=9000"

  # password manager
  # https://www.techaddressed.com/tutorials/vaultwarden-docker-compose/#smtp-email-account
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server:latest
    profiles: ["tools", "all"]
    networks:
      - t2_proxy
    restart: unless-stopped
    volumes:
      - $DOCKERDIR/appdata/vaultwarden:/data
    ports:
      - 9991:80
    environment:
      - DOMAIN=https://vaultwarden.$DOMAINNAME_CLOUD_SERVER
      - LOGIN_RATELIMIT_MAX_BURST=10
      - LOGIN_RATELIMIT_SECONDS=60
      - ADMIN_RATELIMIT_MAX_BURST=10
      - ADMIN_RATELIMIT_SECONDS=60
      - ADMIN_TOKEN=$VAULTWARDEN_TOKEN
      - SENDS_ALLOWED=true
      - EMERGENCY_ACCESS_ALLOWED=true
      - WEB_VAULT_ENABLED=true
    labels:
      - "sablier.enable=true"
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.vaultwarden-rtr.entrypoints=https"
      - "traefik.http.routers.vaultwarden-rtr.rule=Host(`vaultwarden.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.vaultwarden-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.vaultwarden-rtr.service=vaultwarden-svc"
      - "traefik.http.services.vaultwarden-svc.loadbalancer.server.port=80"

  # https://github.com/benbusby/whoogle-search/blob/main/docker-compose-traefik.yaml
  whoogle:
    image: ${WHOOGLE_IMAGE:-benbusby/whoogle-search}
    container_name: whoogle
    restart: unless-stopped
    pids_limit: 50
    mem_limit: 256mb
    memswap_limit: 256mb
    profiles: ["tools", "all"]
    # user debian-tor from tor package
    user: whoogle
    # security_opt:
    #   - no-new-privileges
    # cap_drop:
    #   - ALL
    networks:
      - t2_proxy
    tmpfs:
      - /config/:size=10M,uid=927,gid=927,mode=1700
      # - /var/lib/tor/:size=15M,uid=927,gid=927,mode=1700
      # - /run/tor/:size=1M,uid=927,gid=927,mode=1700
    environment: # Uncomment to configure environment variables
      # Site alternative configurations, uncomment to enable
      # Note: If not set, the feature will still be available
      # with default values.
      - WHOOGLE_ALT_TW=farside.link/nitter
      - WHOOGLE_ALT_YT=farside.link/invidious
      - WHOOGLE_ALT_IG=farside.link/bibliogram/u
      - WHOOGLE_ALT_RD=farside.link/libreddit
      - WHOOGLE_ALT_MD=farside.link/scribe
      - WHOOGLE_ALT_TL=farside.link/lingva
      - WHOOGLE_ALT_IMG=farside.link/rimgo
      - WHOOGLE_ALT_WIKI=farside.link/wikiless
      - WHOOGLE_ALT_IMDB=farside.link/libremdb
      - WHOOGLE_ALT_QUORA=farside.link/quetre
      - WHOOGLE_CONFIG_DISABLE=1
      - WHOOGLE_CONFIG_SEARCH_LANGUAGE=lang_en
      - WHOOGLE_CONFIG_GET_ONLY=1
      - WHOOGLE_CONFIG_COUNTRY=US
      - WHOOGLE_CONFIG_PREFERENCES_ENCRYPTED=1
      # - WHOOGLE_CONFIG_PREFERENCES_KEY="NEEDS_TO_BE_MODIFIED"
    # env_file: # Alternatively, load variables from whoogle.env
    #   - whoogle.env
    ports:
      - 8202:5000
    labels:
      - sablier.enable=true
      - sablier.group=mygroup
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.whoogle-rtr.entrypoints=https"
      - "traefik.http.routers.whoogle-rtr.rule=Host(`whoogle.$DOMAINNAME_CLOUD_SERVER`)"
      ## Middlewares
      - "traefik.http.routers.whoogle-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.whoogle-rtr.service=whoogle-svc"
      - "traefik.http.services.whoogle-svc.loadbalancer.server.port=5000"
      ## Homepage
      - homepage.group=Tools
      - homepage.name=Whoogle
      - homepage.icon=whoogle.png
      - homepage.href=https://whoogle.mirwin.net
      - homepage.description=Google proxy
      # - homepage.weight=2

#   # Nginx - Web Server
#   nginx:
#     container_name: nginx
#     image: nginx:1.20 # 1.18 # Updated 8/9/2021
#     # security_opt:
#     #   - no-new-privileges:true
#     restart: unless-stopped
#     profiles: ["core", "all"]
#     networks:
#       - t2_proxy
#     depends_on:
#       # - php7
#       - redis
#     volumes:
#       - /etc/localtime:/etc/localtime:ro
#       - /etc/timezone:/etc/timezone:ro
#       - $DOCKERDIR/logs/web/nginx:/var/log/nginx
#       - $DOCKERDIR/appdata/nginx:/etc/nginx
#       - $DOCKERDIR/appdata/sites/shb/html:/var/www/html/shb
#       - $DOCKERDIR/logs/web/wordpress/debug.log:/var/www/html/shb/wp-content/debug.log
#       - $DOCKERDIR/appdata/sites/shb/beta:/var/www/html/beta
#       # - $DOCKERDIR/appdata/sites/khub/html:/var/www/html/khub
#       - $DOCKERDIR/appdata/sites/dash/html:/var/www/html/dash
#     secrets:
#       - htpasswd
#     labels:
#       - "traefik.enable=true"
#       ## HTTP Routers SHB (WordPress) Auth
#       - "traefik.http.routers.nginx-shb-auth-rtr.entrypoints=https"
#       - "traefik.http.routers.nginx-shb-auth-rtr.rule=Host(`www.$DOMAINNAME_CLOUD_SERVER`) && Path(`/wp-login.php`)"
#       - "traefik.http.routers.nginx-shb-auth-rtr.priority=100"
#       ## HTTP Routers SHB (WordPress) Bypass
#       - "traefik.http.routers.nginx-shb-rtr.entrypoints=https"
#       - "traefik.http.routers.nginx-shb-rtr.rule=Host(`$DOMAINNAME_CLOUD_SERVER`) || Host(`www.$DOMAINNAME_CLOUD_SERVER`)"
#       - "traefik.http.routers.nginx-shb-rtr.priority=99"
#       ## HTTP Routers SHB Beta (WordPress)
#       - "traefik.http.routers.nginx-shb-beta-rtr.entrypoints=https"
#       - "traefik.http.routers.nginx-shb-beta-rtr.rule=Host(`beta.$DOMAINNAME_CLOUD_SERVER`)"
#       ## HTTP Routers DASH (non-WordPress)
#       - "traefik.http.routers.nginx-dash-rtr.entrypoints=https"
#       - "traefik.http.routers.nginx-dash-rtr.rule=Host(`dash.$DOMAINNAME_CLOUD_SERVER`)"
#       ## HTTP Routers KHUB (non-WordPress)
#       # - "traefik.http.routers.nginx-khub-rtr.entrypoints=https"
#       # - "traefik.http.routers.nginx-khub-rtr.rule=Host(`$DOMAINNAME_KHUB`) || Host(`www.$DOMAINNAME_KHUB`)"
#       # Redirect shb non-www to www middleware
#       - "traefik.http.middlewares.shb-redirect.redirectregex.regex=^https?://$DOMAINNAME_CLOUD_SERVER/(.*)"
#       - "traefik.http.middlewares.shb-redirect.redirectregex.replacement=https://www.$DOMAINNAME_CLOUD_SERVER/$${1}"
#       - "traefik.http.middlewares.shb-redirect.redirectregex.permanent=true"
#       # Redirect khub non-www to www middleware
#       # - "traefik.http.middlewares.khub-redirect.redirectregex.regex=^https?://$DOMAINNAME_KHUB/(.*)"
#       # - "traefik.http.middlewares.khub-redirect.redirectregex.replacement=https://www.$DOMAINNAME_KHUB/$${1}"
#       # - "traefik.http.middlewares.khub-redirect.redirectregex.permanent=true"
#       ## Middlewares
#       # - "traefik.http.routers.nginx-khub-rtr.middlewares=khub-redirect,chain-no-auth@file"
#       - "traefik.http.routers.nginx-shb-rtr.middlewares=shb-redirect,chain-no-auth-wp@file"
#       #- "traefik.http.routers.nginx-shb-auth-rtr.middlewares=shb-redirect,chain-oauth-wp@file"
#       - "traefik.http.routers.nginx-shb-auth-rtr.middlewares=shb-redirect,chain-no-auth-wp@file"
#       - "traefik.http.routers.nginx-dash-rtr.middlewares=chain-oauth@file"
#       - "traefik.http.routers.nginx-shb-beta-rtr.middlewares=chain-oauth@file"
#       ## HTTP Services
#       - "traefik.http.routers.nginx-shb-rtr.service=nginx-svc"
#       - "traefik.http.routers.nginx-shb-auth-rtr.service=nginx-svc"
#       # - "traefik.http.routers.nginx-khub-rtr.service=nginx-svc"
#       - "traefik.http.routers.nginx-dash-rtr.service=nginx-svc"
#       - "traefik.http.routers.nginx-shb-beta-rtr.service=nginx-svc"
#       - "traefik.http.services.nginx-svc.loadbalancer.server.port=80"

#   # PHP - Hypertext Preprocessor
#   php7:
#     container_name: php7
#     image: php:7.4-fpm-custom
#     # security_opt:
#     #   - no-new-privileges:true
#     restart: unless-stopped
#     profiles: ["core", "all"]
#     networks:
#       - t2_proxy
#     build:
#       context: $DOCKERDIR/custom/
#       dockerfile: Dockerfile-php7
#     user: $PUID:$PGID # allows upgrading WP and plugins
#     volumes:
#       - $DOCKERDIR/appdata/sites/shb/html:/var/www/html/shb
#       - $DOCKERDIR/appdata/sites/shb/beta:/var/www/html/beta
#       - $DOCKERDIR/appdata/php/php7:/usr/local/etc/php
#       # - $DOCKERDIR/appdata/sites/khub/html:/var/www/html/khub
#       - $DOCKERDIR/appdata/sites/dash/html:/var/www/html/dash

  # https://github.com/matrix-org/synapse/blob/develop/contrib/docker/docker-compose.yml
  # synapse:
  #   image: matrixdotorg/synapse:latest
  #   container_name: synapse
  #   restart: unless-stopped
  #   profiles: ["core", "all"]
  #   networks:
  #     - t2_proxy
  #   # See the readme for a full documentation of the environment settings
  #   environment:
  #     - SYNAPSE_CONFIG_PATH=/conf/homeserver.yaml
  #     - VIRTUAL_HOST="synapse.$DOMAINNAME_CLOUD_SERVER"
  #     - LETSENCRYPT_HOST="synapse.$DOMAINNAME_CLOUD_SERVER"
  #     - SYNAPSE_SERVER_NAME="synapse.$DOMAINNAME_CLOUD_SERVER"
  #     - SYNAPSE_REPORT_STATS="yes"
  #     - VIRTUAL_PORT=8448
      
  #   volumes:
  #     - $DOCKERDIR/appdata/synapse:/data
  #   ports:
  #     - 8448:8448/tcp
  #   labels:
  #     # Alternatively, for Traefik version 2.0:
  #     - traefik.enable=true
  #     - traefik.http.routers.http-synapse.entryPoints=http
  #     - traefik.http.routers.http-synapse.rule=Host(`synapse.$DOMAINNAME_CLOUD_SERVER`)
  #     - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
  #     - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true
  #     - traefik.http.routers.http-synapse.middlewares=https_redirect
  #     - traefik.http.routers.https-synapse.entryPoints=https
  #     - traefik.http.routers.https-synapse.rule=Host(`synapse.$DOMAINNAME_CLOUD_SERVER`)
  #     - traefik.http.routers.https-synapse.service=synapse
  #     - traefik.http.routers.https-synapse.tls=true
  #     - traefik.http.services.synapse.loadbalancer.server.port=8448
  #     - traefik.http.routers.https-synapse.tls.certResolver=le-ssl

#   tubearchivist:
#     container_name: tubearchivist
#     restart: unless-stopped
#     image: bbilly1/tubearchivist
#     ports:
#       - 8999:8000
#     volumes:
#         - $DATADIR/Youtube:/youtube
#     environment:
#       ES_URL: http://elasticsearch:9200    # needs protocol e.g. http and port
#       REDIS_HOST: redis                    # don't add protocol
#       HOST_UID: $PUID
#       HOST_GID: $PGID
#       TA_HOST: tubearchivist.mirwin.net    # set your host name
#       TA_USERNAME: tubearchivist           # your initial TA credentials
#       TA_PASSWORD: $TA_PASSWORD            # your initial TA credentials
#       ELASTIC_PASSWORD: $ELASTIC_PASSWORD  # set password for Elasticsearch
#       TZ: $TZ
#     healthcheck:
#       test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
#       interval: 2m
#       timeout: 10s
#       retries: 3
#       start_period: 30s
#     depends_on:
#       - elasticsearch
#       - redis
#     labels:
#       - "traefik.enable=true"
#       ## HTTP Routers Auth
#       - "traefik.http.routers.tubearchivist-rtr.entrypoints=https"
#       - "traefik.http.routers.tubearchivist-rtr.rule=Host(`tube.$DOMAINNAME_CLOUD_SERVER`)"
#       ## Middlewares
#       - "traefik.http.routers.tubearchivist-rtr.middlewares=chain-oauth@file"
#       ## HTTP Services
#       - "traefik.http.routers.tubearchivist-rtr.service=tubearchivist-svc"
#       - "traefik.http.services.tubearchivist-svc.loadbalancer.server.port=5055"
#       ## Homepage
#       - homepage.group=Manage
#       - homepage.name=TubeArchivist
#       - homepage.icon=tubearchivist.png
#       - homepage.href=https://tubearchivist.mirwin.net
#       - homepage.description=Youtube stuff
#       # - homepage.weight=1
#       - homepage.widget.type=tubearchivist
#       - homepage.widget.url=http://tubearchivist:5055
#       - homepage.widget.key=${TUBEARCHIVIST_API_KEY}

  # searx:
  #   container_name: searx
  #   image: searxng/searxng:latest
  #   networks:
  #     # - searxng
  #     - t2_proxy
  #   ports:
  #    - "127.0.0.1:4080:8080"
  #   volumes:
  #     - $DOCKERDIR/appdata/searxng:/etc/searxng:rw
  #   environment:
  #     - SEARXNG_BASE_URL=https://searx.$DOMAINNAME_CLOUD_SERVER # ${SEARXNG_HOSTNAME:-localhost}/
  #   # cap_drop:
  #   #   - ALL
  #   # cap_add:
  #   #   - CHOWN
  #   #   - SETGID
  #   #   - SETUID
  #   logging:
  #     driver: "json-file"
  #     options:
  #       max-size: "1m"
  #       max-file: "1"
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.searx-rtr.entrypoints=https"
  #     - "traefik.http.routers.searx-rtr.rule=Host(`searx.$DOMAINNAME_CLOUD_SERVER`)"
  #     ## Middlewares
  #     - "traefik.http.routers.searx-rtr.middlewares=chain-oauth@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.searx-rtr.service=searx-svc"
  #     - "traefik.http.services.searx-svc.loadbalancer.server.port=8080"

# networks:
#   searxng:
#     ipam:
#       driver: default

  # https://github.com/wallabag/docker
  # wallabag:
  #   image: wallabag/wallabag
  #   container_name: wallabag
  #   networks:
  #     - t2_proxy
  #   restart: unless-stopped
  #   environment:
  #     # - SYMFONY__ENV__MAILER_DSN=smtp://127.0.0.1
  #     # - SYMFONY__ENV__FROM_EMAIL=wallabag@example.com
  #     - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.$DOMAINNAME_CLOUD_SERVER
  #     # - SYMFONY__ENV__SERVER_NAME="Barcelona instance"
  #   ports:
  #     - "3124:80"
  #   volumes:
  #     - $DOCKERDIR/appdata/wallabag:/config
  #   #   - /opt/wallabag/images:/var/www/wallabag/web/assets/images
  #   # healthcheck:
  #   #   test: ["CMD", "wget" ,"--no-verbose", "--tries=1", "--spider", "http://localhost"]
  #   #   interval: 1m
  #   #   timeout: 3s
  #   labels:
  #     - "traefik.enable=true"
  #     ## HTTP Routers
  #     - "traefik.http.routers.wallabag-rtr.entrypoints=https"
  #     - "traefik.http.routers.wallabag-rtr.rule=Host(`wallabag.$DOMAINNAME_CLOUD_SERVER`)"
  #     ## Middlewares
  #     - "traefik.http.routers.wallabag-rtr.middlewares=chain-oauth@file"
  #     ## HTTP Services
  #     - "traefik.http.routers.wallabag-rtr.service=wallabag-svc"
  #     - "traefik.http.services.wallabag-svc.loadbalancer.server.port=80"
