# version: "3.9"

services:
  elasticsearch:
    image: elasticsearch:8.9.0 # bbilly1/tubearchivist-es
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - "ELASTIC_PASSWORD=$ELASTIC_PASSWORD"       # matching Elasticsearch password
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=true"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/data/snapshot"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ${DOCKERDIR:-/opt/docker}/appdata/elasticsearch:/usr/share/elasticsearch/data    # check for permission error when using bind mount, see readme
    expose:
      - "9200"

  # Redis - Key-value Store
  redis:
    container_name: redis
    image: redis:latest # redis:alpine
    # security_opt:
    #   - no-new-privileges:true
    restart: unless-stopped
    profiles: ["core", "all"]
    networks:
      - t2_proxy
    # command: redis-server --save "" --appendonly "no"
    entrypoint: redis-server --appendonly yes --maxmemory 1073741824 --maxmemory-policy allkeys-lru # --requirepass $REDIS_PASSWORD 
    ports:
      - "6379:6379"
    # tmpfs:
    #   - /var/lib/redis
    # cap_drop:
    #   - ALL
    # cap_add:
    #   - SETGID
    #   - SETUID
    #   - DAC_OVERRIDE
    volumes:
      - ${DOCKERDIR:-/opt/docker}/appdata/redis/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
