# Download Services
# Download managers, torrent clients, and related applications


networks:
  t2_proxy:
    external: true

services:
  # jDownloader - Download management
  jdownloader:
    image: jlesage/jdownloader-2:v1.8.0
    container_name: jdownloader
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    profiles: ["apps", "all"]
    networks:
      - t2_proxy
    ports:
      - "${JDOWNLOADER_PORT:-5801}:5800"
    volumes:
      - ${DOWNLOADSDIR:-$DATADIR/downloads}:/data/downloads
      - ${DOCKERDIR:-/opt/docker}/appdata/jdownloader:/config
    environment:
      USER_ID: ${PUID:-1000}
      GROUP_ID: ${PGID:-1000}
      TZ: ${TZ:-UTC}
      UMASK: 002
      KEEP_APP_RUNNING: 1
      CLEAN_TMP_DIR: 1
      DISPLAY_WIDTH: 1600
      DISPLAY_HEIGHT: 960
      VNC_PASSWORD: $JDOWN_VNC_PASSWD
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5800/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.jdownloader-rtr.entrypoints=https"
      - "traefik.http.routers.jdownloader-rtr.rule=Host(`jdown.${DOMAINNAME_CLOUD_SERVER}`)"
      ## Middlewares
      - "traefik.http.routers.jdownloader-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.jdownloader-rtr.service=jdownloader-svc"
      - "traefik.http.services.jdownloader-svc.loadbalancer.server.port=5800"
      # ## Homepage
      - homepage.group=Downloaders
      - homepage.name=JDownloader
      - homepage.icon=jdowloader.png
      - homepage.href=https://jdown.${DOMAINNAME_CLOUD_SERVER}
      - homepage.description=Download files
      - homepage.weight=5

  # qBittorrent - BitTorrent Client
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    restart: unless-stopped
    profiles: ["downloads", "all"]
    networks:
      - t2_proxy
    ports:
      - "${QBITTORRENT_PORT:-8080}:8080"
      - "6881:6881"
      - "6881:6881/udp"
    volumes:
      - ${DOCKERDIR:-/opt/docker}/appdata/qbittorrent:/config
      - $DATADIR/Downloads:/downloads
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - sablier.enable=true
      - sablier.group=mygroup
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.qbittorrent-rtr.entrypoints=https"
      - "traefik.http.routers.qbittorrent-rtr.rule=Host(`qbittorrent.${DOMAINNAME_CLOUD_SERVER}`)"
      ## Middlewares
      - "traefik.http.routers.qbittorrent-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.qbittorrent-rtr.service=qbittorrent-svc"
      - "traefik.http.services.qbittorrent-svc.loadbalancer.server.port=8080"
      ## Homepage
      - homepage.group=Downloaders
      - homepage.name=qBittorrent
      - homepage.icon=qbittorrent.png
      - homepage.href=https://qbittorrent.${DOMAINNAME_CLOUD_SERVER}
      - homepage.description=BitTorrent client
      - homepage.weight=3

  # Transmission - BitTorrent Client
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    restart: unless-stopped
    profiles: ["downloads", "all"]
    networks:
      - t2_proxy
    ports:
      - "${TRANSMISSION_PORT:-9091}:9091"
      - "51413:51413"
      - "51413:51413/udp"
    volumes:
      - ${DOCKERDIR:-/opt/docker}/appdata/transmission:/config
      - $DATADIR/Downloads:/downloads
      - $DATADIR/Watch:/watch
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9091/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - sablier.enable=true
      - sablier.group=mygroup
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.transmission-rtr.entrypoints=https"
      - "traefik.http.routers.transmission-rtr.rule=Host(`transmission.${DOMAINNAME_CLOUD_SERVER}`)"
      ## Middlewares
      - "traefik.http.routers.transmission-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.transmission-rtr.service=transmission-svc"
      - "traefik.http.services.transmission-svc.loadbalancer.server.port=9091"
      ## Homepage
      - homepage.group=Downloaders
      - homepage.name=Transmission
      - homepage.icon=transmission.png
      - homepage.href=https://transmission.${DOMAINNAME_CLOUD_SERVER}
      - homepage.description=BitTorrent client
      - homepage.weight=4

  # NZBGet - Usenet Downloader
  nzbget:
    image: lscr.io/linuxserver/nzbget:latest
    container_name: nzbget
    restart: unless-stopped
    profiles: ["downloads", "all"]
    networks:
      - t2_proxy
    ports:
      - "${NZBGET_PORT:-6789}:6789"
    volumes:
      - ${DOCKERDIR:-/opt/docker}/appdata/nzbget:/config
      - $DATADIR/Downloads:/downloads
      - $DATADIR/Intermediates:/intermediates
      - $DATADIR/NZB:/nzb
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:6789/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - sablier.enable=true
      - sablier.group=mygroup
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.nzbget-rtr.entrypoints=https"
      - "traefik.http.routers.nzbget-rtr.rule=Host(`nzbget.${DOMAINNAME_CLOUD_SERVER}`)"
      ## Middlewares
      - "traefik.http.routers.nzbget-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.nzbget-rtr.service=nzbget-svc"
      - "traefik.http.services.nzbget-svc.loadbalancer.server.port=6789"
      ## Homepage
      - homepage.group=Downloaders
      - homepage.name=NZBGet
      - homepage.icon=nzbget.png
      - homepage.href=https://nzbget.${DOMAINNAME_CLOUD_SERVER}
      - homepage.description=Usenet downloader
      - homepage.weight=5

  # SABnzbd - Usenet Downloader
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    restart: unless-stopped
    profiles: ["downloads", "all"]
    networks:
      - t2_proxy
    ports:
      - "${SABNZBD_PORT:-8080}:8080"
    volumes:
      - ${DOCKERDIR:-/opt/docker}/appdata/sabnzbd:/config
      - $DATADIR/Downloads:/downloads
      - $DATADIR/Intermediates:/intermediates
      - $DATADIR/NZB:/nzb
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
    labels:
      - sablier.enable=true
      - sablier.group=mygroup
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.sabnzbd-rtr.entrypoints=https"
      - "traefik.http.routers.sabnzbd-rtr.rule=Host(`sabnzbd.${DOMAINNAME_CLOUD_SERVER}`)"
      ## Middlewares
      - "traefik.http.routers.sabnzbd-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.sabnzbd-rtr.service=sabnzbd-svc"
      - "traefik.http.services.sabnzbd-svc.loadbalancer.server.port=8080"
      ## Homepage
      - homepage.group=Downloaders
      - homepage.name=SABnzbd
      - homepage.icon=sabnzbd.png
      - homepage.href=https://sabnzbd.${DOMAINNAME_CLOUD_SERVER}
      - homepage.description=Usenet downloader
      - homepage.weight=6 