# Media Services

networks:
  t2_proxy:
    external: true

services:
  # MeTube - YouTube Downloader
  metube:
    image: ghcr.io/alexta69/metube
    container_name: metube
    profiles: ["media", "all"]
    networks:
      - t2_proxy
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ${DOCKERDIR:-/opt/docker}/appdata/metube:/data
      - $DATADIR/Youtube:/downloads
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    labels:
      - "traefik.enable=true"
      ## HTTP Routers Auth
      - "traefik.http.routers.metube-rtr.entrypoints=https"
      - "traefik.http.routers.metube-rtr.rule=Host(`metube.${DOMAINNAME_CLOUD_SERVER}`)"
      ## Middlewares
      - "traefik.http.routers.metube-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.metube-rtr.service=metube-svc"
      - "traefik.http.services.metube-svc.loadbalancer.server.port=8081"
      ## Homepage
      - homepage.group=Admin
      - homepage.name=Metube
      - homepage.href=https://metube.${DOMAINNAME_CLOUD_SERVER}
      - homepage.description=Youtube frontend
      - homepage.weight=1

  # Pinchflat - YouTube RSS Feed Manager
  pinchflat:
    image: ghcr.io/kieraneglin/pinchflat:latest
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    profiles: ["media", "all"]
    networks:
      - t2_proxy
    volumes:
      - ${DOCKERDIR:-/opt/docker}/appdata/pinchflat:/app/data
    restart: unless-stopped
    labels:
      - sablier.enable=true
      - sablier.group=mygroup
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.pinchflat-rtr.entrypoints=https"
      - "traefik.http.routers.pinchflat-rtr.rule=Host(`pinchflat.${DOMAINNAME_CLOUD_SERVER}`)"
      ## Middlewares
      - "traefik.http.routers.pinchflat-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.pinchflat-rtr.service=pinchflat-svc"
      - "traefik.http.services.pinchflat-svc.loadbalancer.server.port=8080"
      ## Homepage
      - homepage.group=Media
      - homepage.name=Pinchflat
      - homepage.icon=pinchflat.png
      - homepage.href=https://pinchflat.${DOMAINNAME_CLOUD_SERVER}
      - homepage.description=YouTube RSS Feed Manager
      - homepage.weight=4

  # Picard - Music Tagging
  picard:
    image: mikenye/picard:latest
    container_name: picard
    restart: unless-stopped
    profiles: ["media", "all"]
    networks:
      - t2_proxy
    ports:
      - "5800:5800"
    volumes:
      - ${DOCKERDIR:-/opt/docker}/appdata/picard:/config
      - $DATADIR/Music:/music
    environment:
      TZ: ${TZ:-UTC}
      PUID: ${PUID:-1000}
      PGID: ${PGID:-1000}
    labels:
      - sablier.enable=true
      - sablier.group=mygroup
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.picard-rtr.entrypoints=https"
      - "traefik.http.routers.picard-rtr.rule=Host(`picard.${DOMAINNAME_CLOUD_SERVER}`)"
      ## Middlewares
      - "traefik.http.routers.picard-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.picard-rtr.service=picard-svc"
      - "traefik.http.services.picard-svc.loadbalancer.server.port=5800"
      ## Homepage
      - homepage.group=Media
      - homepage.name=Picard
      - homepage.icon=picard.png
      - homepage.href=https://picard.${DOMAINNAME_CLOUD_SERVER}
      - homepage.description=Music Tagging
      - homepage.weight=6
